<?php
/**
 * @var \Skuiq\SyncModule\Block\Config $block
 */
?>
<div class="skuiq-left-panel">
  <img class="skuiq-mg2-logo" src="https://static.magento.com/sites/all/themes/magento/logo.svg">
  <br>
  <div class="arrow"></div>
  <br><br>
  <img class="skuiq-logo" src="http://boutiika-assets.s3.amazonaws.com/our_brand_logos/skuIQ-logo-black-small.png"/>
</div>
<?php if ($block->isConnected()) {?>
  <div class="skuiq-right-panel vcenter" >
        <div class="connect_status live"></div>
        Connected to SkuIQ
        <span class="details">
        </span>
        <br><br>
        <div class="connect_status time"></div>
        Syncs in real time.
        <br><br>
  </div>
<?php
} else {
  ?>
     <div class="skuiq-right-panel">
       <h1>Connect your Magento to Sku IQ</h1>
       <p class="lightgray"> Connect Magento to SkuIQ to sync data to and from Clover, Square, Lightspeed, ERPLY and more in real time. Keep inventory in sync and accurate.
         </p>
         <br>
       <p id="intro_string">
         Welcome to Sku IQ!  <a href="/auto-shop/getting-started">Here is how to get started.</a>
       </p>
       <br>
       <p>
         Questions? Complicated setup?
         <a href="#" onclick="toggleZendeskHelp()">Contact us</a>
         and get help from an inventory expert.
       </p>
       <br>
       <p> We have sucessfully created an integration in your Magento install. Please click on the link below to activate it and start SkuIQ! </p>
       <form target="_blank" action="https://app.chopzu.com/register/magento2?" method="post">
          <?php
            $oauth = $block->getOauthData();
            $store_info = $block->getStoreInfo();
           ?>
          <input type="hidden" name="oauth_consumer_key" value="<?php echo $oauth['oauth_consumer_key'] ?>">
          <input type="hidden" name="store_base_url" value="<?php echo $oauth['store_base_url'] ?>">
          <input type="hidden" name="signup_store_name" value="<?php echo $store_info['signup_store_name'] ?>">
          <input type="hidden" name="signup_store_phone" value="<?php echo $store_info['signup_store_phone'] ?>">
          <input type="hidden" name="signup_store_address1" value="<?php echo $store_info['signup_store_address1'] ?>">
          <input type="hidden" name="signup_store_city" value="<?php echo $store_info['signup_store_city'] ?>">
          <input type="hidden" name="signup_store_country" value="<?php echo $store_info['signup_store_country'] ?>">
          <input type="hidden" name="signup_store_state" value="<?php echo $store_info['signup_store_state'] ?>">
          <input type="hidden" name="signup_store_zip" value="<?php echo $store_info['signup_store_zip'] ?>">
          <input type="hidden" name="magento_version" value="<?php echo $store_info['magento_version'] ?>">

          <input class="mg_button" type="submit" value="Access Skuiq">

        </form>
     </div>
<?php
  }
?>
